musicmeta_project/musicmeta/urls.py
from django.urls import path
from . import views


app_name = 'musicmeta'
urlpatterns = [
    path('', views.index, name="index"),
    path('artist/<str:artist_id>/<int:page>/', views.artist, name="artist")
]

musicmeta_project/musicmeta_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('musicmeta.urls')),
    path('admin/', admin.site.urls),
]

musicmeta_project/musicmeta/models.py
from django.db import models

# Create your models here.

musicmeta_project/musicmeta/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template.defaulttags import register
from musicbrainzngs import *
import math

# Create your views here.


@register.filter
def get_begin(dictionary):
  return dictionary.get('life-span').get('begin')


@register.filter
def get_release_date(dictionary):
  return dictionary.get('first-release-date')


def index(request):
  query = request.GET.get('searchInput', False)
  if query:
    set_format('json')
    result = search_artists(query, strict=True)
    return render(request, 'musicmeta/index.html', {'artists': result["artists"]})
  else:
    return render(request, 'musicmeta/index.html')


def artist(request, artist_id, page):
  result = browse_release_groups(artist_id, limit=100, offset=page*100)
  print(result)
  count = result['release-group-count']
  pages = math.ceil(count / 100)

  albums, album_compilations, album_lives, singles, single_lives, single_remixes, single_soundtracks, eps, ep_lives, broadcasts, broadcast_lives, others = [
  ], [], [], [], [], [], [], [], [], [], [], []
  for release in result["release-group-list"]:
    if 'secondary-type-list' not in release and release['primary-type'] == 'Album':
      albums.append(release)
    elif 'secondary-type-list' not in release and release['primary-type'] == 'Single':
      singles.append(release)
    elif 'secondary-type-list' not in release and release['primary-type'] == 'EP':
      eps.append(release)
    elif 'secondary-type-list' not in release and release['primary-type'] == 'Broadcast':
      broadcasts.append(release)
    elif release['primary-type'] == 'Album' and release['secondary-type-list'][0] == 'Compilation':
      album_compilations.append(release)
    elif release['primary-type'] == 'Album' and release['secondary-type-list'][0] == 'Live':
      album_lives.append(release)
    elif release['primary-type'] == 'Single' and release['secondary-type-list'][0] == 'Live':
      single_lives.append(release)
    elif release['primary-type'] == 'Single' and release['secondary-type-list'][0] == 'Remix':
      single_remixes.append(release)
    elif release['primary-type'] == 'Single' and release['secondary-type-list'][0] == 'Soundtrack':
      single_soundtracks.append(release)
    elif release['primary-type'] == 'EP' and release['secondary-type-list'][0] == 'Live':
      ep_lives.append(release)
    elif release['primary-type'] == 'Broadcast' and release['secondary-type-list'][0] == 'Live':
      broadcast_lives.append(release)
    else:
      others.append(release)
  albums.sort(key=lambda x: x['first-release-date'])
  album_compilations.sort(key=lambda x: x['first-release-date'])
  album_lives.sort(key=lambda x: x['first-release-date'])
  singles.sort(key=lambda x: x['first-release-date'])
  single_lives.sort(key=lambda x: x['first-release-date'])
  single_remixes.sort(key=lambda x: x['first-release-date'])
  single_soundtracks.sort(key=lambda x: x['first-release-date'])
  eps.sort(key=lambda x: x['first-release-date'])
  ep_lives.sort(key=lambda x: x['first-release-date'])
  broadcasts.sort(key=lambda x: x['first-release-date'])
  broadcast_lives.sort(key=lambda x: x['first-release-date'])
  others.sort(key=lambda x: x['first-release-date'])
  return render(request, 'musicmeta/artist.html', {"pages": range(pages), "page": page, "artist_id": artist_id, "albums": albums, "album_compilations": album_compilations, "album_lives": album_lives, "singles": singles, "single_lives": single_lives, "single_remixes": single_remixes, "single_soundtracks": single_soundtracks, "eps": eps, "ep_lives": ep_lives, "broadcasts": broadcasts, "broadcast_lives": broadcast_lives, "others": others})
  return HttpResponse("You are at artists")

musicmeta_project/musicmeta/templates/musicmeta/artist.html
<!DOCTYPE html>
<html>
  <head>
    <title>MUSICMETA</title>
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'musicmeta/styles.css' %}"
    />
  </head>
  <body>
    {% if albums %}
    <h3 class="heading">Album</h3>
    {% endif %} {% for album in albums %}
    <a href="/release-group/{{album.id}}/">{{album.title}}</a>
    <div>{{album|get_release_date}}</div>
    {% endfor %} {% if album_compilations %}
    <h3 class="heading">Album + Compilation</h3>
    {% endif %} {% for album_compilation in album_compilations %}
    <a href="/release-group/{{album_compilation.id}}/"
      >{{album_compilation.title}}</a
    >
    <div>{{album_compilation|get_release_date}}</div>
    {% endfor %} {% if album_lives %}
    <h3 class="heading">Album + Live</h3>
    {% endif %} {% for album_live in album_lives %}
    <a href="/release-group/{{album_live.id}}/">{{album_live.title}}</a>
    <div>{{album_live|get_release_date}}</div>
    {% endfor %} {% if singles %}
    <h3 class="heading">Single</h3>
    {% endif %} {% for single in singles %}
    <a href="/release-group/{{single.id}}/">{{single.title}}</a>
    <div>{{single|get_release_date}}</div>
    {% endfor %} {% if single_lives %}
    <h3 class="heading">Single + Live</h3>
    {% endif %} {% for single_live in single_lives %}
    <a href="/release-group/{{single_live.id}}/">{{single_live.title}}</a>
    <div>{{single_live|get_release_date}}</div>
    {% endfor %} {% if single_remixes %}
    <h3 class="heading">Single + Remix</h3>
    {% endif %} {% for single_remix in single_remixes %}
    <a href="/release-group/{{single_remix.id}}/">{{single_remix.title}}</a>
    <div>{{single_remix|get_release_date}}</div>
    {% endfor %} {% if single_remixes %}
    <h3 class="heading">Single + Remix</h3>
    {% endif %} {% for single_remix in single_remixes %}
    <a href="/release-group/{{single_remix.id}}/">{{single_remix.title}}</a>
    <div>{{single_remix|get_release_date}}</div>
    {% endfor %} {% if single_soundtracks %}
    <h3 class="heading">Single + Soundtrack</h3>
    {% endif %} {% for single_soundtrack in single_soundtracks %}
    <a href="/release-group/{{single_soundtrack.id}}/"
      >{{single_soundtrack.title}}</a
    >
    <div>{{single_soundtrack|get_release_date}}</div>
    {% endfor %} {% if eps %}
    <h3 class="heading">EP</h3>
    {% endif %} {% for ep in eps %}
    <a href="/release-group/{{ep.id}}/">{{ep.title}}</a>
    <div>{{ep|get_release_date}}</div>
    {% endfor %} {% if ep_lives %}
    <h3 class="heading">EP + Live</h3>
    {% endif %} {% for ep_live in ep_lives %}
    <a href="/release-group/{{ep_live.id}}/">{{ep_live.title}}</a>
    <div>{{ep_live|get_release_date}}</div>
    {% endfor %} {% if broadcasts %}
    <h3 class="heading">Broadcast</h3>
    {% endif %} {% for broadcast in broadcasts %}
    <a href="/release-group/{{broadcast.id}}/">{{broadcast.title}}</a>
    <div>{{broadcast|get_release_date}}</div>
    {% endfor %} {% if broadcast_lives %}
    <h3 class="heading">Broadcast + Live</h3>
    {% endif %} {% for broadcast_live in broadcast_lives %}
    <a href="/release-group/{{broadcast_live.id}}/">{broadcast_live.title}}</a>
    <div>{{broadcast_live|get_release_date}}</div>
    {% endfor %} {% if others %}
    <h3 class="heading">Other</h3>
    {% endif %} {% for other in others %}
    <a href="/release-group/{{other.id}}/">{{other.title}}</a>
    <div>{{other|get_release_date}}</div>
    {% endfor %} {% for page in pages %}
    <a href="/artist/{{artist_id}}/{{page}}">{{page}}</a>
    {% endfor %}
  </body>
</html>

musicmeta_project/musicmeta/templates/musicmeta/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Musicmeta</title>
  </head>
  <body>
    <h1>MUSICMETA</h1>
    <form action="{% url 'musicmeta:index' %}" method="get">
      <input
        type="search"
        name="searchInput"
        id="searchInput"
        placeholder="Enter query"
      />
      <input type="submit" value="Search" id="searchBtn" />
    </form>
    <div>
      {% if artists %} {% for artist in artists %}
      <div class="card">
        <a href="/artist/{{artist.id}}/1"><h3>{{artist.name}}</h3></a>
        {% if artist.disambiguation %}
        <div class="disambiguation">{{artist.disambiguation}}</div>
        {% endif%}
        <div>Type: {{artist.type}}</div>
        <div>Begin: {{artist|get_begin}}</div>
        <div>Country: {{artist.country}}</div>
      </div>
      {% endfor %} {% endif %}
    </div>
  </body>
</html>